from interfaces import IGoogleGadget
from Products.qi.report.internal.complex.widgits.datatable import Widgit
from zope.interface import implements
from zope.component.factory import Factory
from Products.PythonScripts.standard import url_quote_plus

"""this is copied google's autogenerated code, kept for reference, but pieces are generated dynamically now, based on object
properties
&amp;up__table_query_url=http%3A%2F%2Flocalhost%3A10495%2Fqiteamspace%2Fdomainproject%2Freport-beta%2Frow-6%2Fwidgit-1%2Fdataurl
&amp;up_title=title2
&amp;up_initialstate=
&amp;up__table_query_refresh_interval=0
&amp;synd=open&amp;
w=800&amp;h=600&amp;
title=mytitle&amp;lang=all&amp;country=ALL&amp;border=%23ffffff%7C3px%2C1px+solid+%23999999&amp;output=js"></script>"""

class GoogleGadgetWidgit(Widgit):
    implements(IGoogleGadget)
    #may be no particular function needed
    def displayblurb(self):
        resultformat='<script src="%s"></script>'
        sourcestring="http://www.gmodules.com/ig/ifr?url=%s%s"%(self.chartObject(),self.buildBigParam())
        return resultformat%sourcestring

    def updateOtherAttribute(self, attribute, value):
        raise NotImplementedError("gadget not yet ready")
    
    xmlurl="http://www.google.com/ig/modules/motionchart.xml"
    width=800;
    height=600;
    def chartObject(self):
        return self.xmlurl
    
    def buildBigParam(self):
        paramdict={
        "up__table_query_url": url_quote_plus('%s/dataurl'%self.absolute_url()),
        "up_title": 'Motion%20Chart',
        'up_initialstate': '',
        'up__table_query_refresh_interval':'0',
        'synd':'open',
        'w':self.width,
        'h':self.height,
        'title':'Motion%20Chart',
        'lang':'all',
        'country':'ALL',
        'border':'%23ffffff%7C3px%2C1px+solid+%23999999',
        'output':'js'
        }
        paramformat='&amp;%s=%s'
        result=""
        for key in paramdict:
            result+=paramformat%(key, str(paramdict[key]))
        return result
        
googlefactory=Factory(GoogleGadgetWidgit, title="lameness incarnate")
    